#!/bin/bash

# Run this commands on gatku container start:
echo "Linking nginx and php config files...";
ln -s /gatku/dev_config/gatku55-nginx.conf /etc/nginx/sites-enabled/
ln -s /gatku/dev_config/gatku55-phpfpm.conf /etc/php/7.2/fpm/pool.d/
chmod 777 -R /gatku/storage/

echo "Restart PHP 7.2 FPM...";
service php7.2-fpm restart

# Start nginx in non demon mode
echo "Start NGINX in non deamon mode."
nginx -g 'daemon off;'

